### ISSUE TITLE
two questions about ratio loss and training patch extraction

### ISSUE THREAD

**Issue by RuibinMa** [vbalnt/tfeat#10]
Hi, thank you for the great work first. May I ask two questions:
1) Basically ratio loss is unsuitable (doesn't converge at all) for keypoint matching according to your paper, so the best choice is ranking with anchor swap. Am I correct? 
2) How are the training patches from Lowe's DoG keypoints extracted? Is it just a fixed-size window cropping or based on the keypoints' scale ( possibly orientation as well?) followed by a normalization step?

Thanks in advance.

**Comment by RuibinMa** [comment]
I'm also wondering how is the network's performance on rotating and scale changing scenarios.

**Comment by vbalnt** [comment]
@RuibinMa please check the test code, where you can find the runtime example using openCV.
