### ISSUE TITLE
how to evaluate the Liberty using Notredame

### ISSUE THREAD

**Issue by hurricane2018** [vbalnt/tfeat#12]
![image](https://user-images.githubusercontent.com/36166137/38773361-15934f52-4018-11e8-8568-c9644670d2de.png)

The test accuracy is always change. Did you get the average precision of the test data ?

I mean, If we train 10 epoch, we can get a precision. If we train 20 epoches, we can get another result. How did you solve this problem ?

**Comment by hurricane2018** [comment]
how many epoches did you use to evaluate a dataset ?

**Comment by hurricane2018** [comment]
In your code, you only train 10 epoches. But if we do several experiments, each time we can get a test result. So did you try several times, and then average them ?

**Comment by vbalnt** [comment]
Training code with the evaluation part is now available as an `ipython` notebook.
