### ISSUE TITLE
Not clear steps for running tfear_demo.py

### ISSUE THREAD

**Issue by abelghazinyan** [vbalnt/tfeat#14]
I am trying to run tfeat_demo.py 2 days already with no luck.
My configurations are Ubuntu 18.04 Cuda 9.0 Cudnn 7.05 Python 2.7 Torch 7
Please can you show details on all dependencies with versions and steps.
There is also a syntax error when running tfeat_demo.py and get_nets.sh not working.
My goal is to run demo in opencv as shown in youtube demo

**Comment by vbalnt** [comment]
Hi, yes I am currently updating the repo, will be ready in a couple of days.
Will keep this open until it's done
