### ISSUE TITLE
Test tfeat descriptor using SIFT keypoint

### ISSUE THREAD

**Issue by hurricane2018** [vbalnt/tfeat#16]
@vbalnt  
Thank you for providing such wonderful work. You have  provided a script to show the correspondence, it shows the TFeat descriptor is obviously better than BRISK. However, if I use SIFT to detect the keypoint, I found the performance is really worse.

 Could you give me some advice on how to solve this problem ?

**Comment by hurricane2018** [comment]
Thank you for your wonderful work, "Learning local feature descriptors with triplets and shallow convolutional neural networks". I test the TFeat descriptor using both BRISK detector and SIFT detector, but the SIFT dector performs really worse.

Example 1.

image.png
![image](https://user-images.githubusercontent.com/36166137/47721228-08d75d80-dc26-11e8-990c-2124fa82a229.png)

Fig 1. SIFT detector and TFeat descriptor

image.png
![image](https://user-images.githubusercontent.com/36166137/47721242-0f65d500-dc26-11e8-9db1-bfbb7e0e6174.png)

Fig 2. BRISK detector and TFeat descriptor

Example 2

image.png
![image](https://user-images.githubusercontent.com/36166137/47721254-155bb600-dc26-11e8-9630-a3bb7d44881b.png)

Fig 3. SIFT detector and TFeat descriptor

image.png
![image](https://user-images.githubusercontent.com/36166137/47721259-1ab90080-dc26-11e8-8076-134be009f102.png)

Fig 4. BRISK detector and TFeat descriptor 


Why the TFeat combined with SIFT detector performs so bad ?

Thank you for your help.

**Comment by edgarriba** [comment]
How do you extract the patches?

**Comment by hurricane2018** [comment]
0. use SIFT to detector the key point
 sift = cv2.xfeatures2d.SIFT_create()
kp1 , des1 = sift.detectAndCompare(img1, None)
kp2 , des2 = sift.detectAndCompare(img2, None)

1. use tfeat_utils.py to extract the patches

        patches = []
        for kp in kpts:
            x,y = kp.pt
            s = kp.size
            a = kp.angle

            s = mag_factor * s / N
            cos = math.cos(a * math.pi / 180.0)
            sin = math.sin(a * math.pi / 180.0)

            M = np.matrix([
                [+s * cos, -s * sin, (-s * cos + s * sin) * N / 2.0 + x],
                [+s * sin, +s * cos, (-s * sin - s * cos) * N / 2.0 + y]])

            patch = cv2.warpAffine(img, M, (N, N),
                                 flags=cv2.WARP_INVERSE_MAP + \
                                 cv2.INTER_CUBIC + cv2.WARP_FILL_OUTLIERS)

            patches.append(patch)

**Comment by edgarriba** [comment]
@hurricane2018 For SIFT, the returned size by OpenCV is not directly the patch size. You might need a magnification factor 7.5.

**Comment by hurricane2018** [comment]
But the result is still not very good. 

![image](https://user-images.githubusercontent.com/36166137/47734299-798b7380-dc40-11e8-805c-ec6ca14e5355.png)
Fig1. BRISK detector + descriptor

![image](https://user-images.githubusercontent.com/36166137/47734350-8c05ad00-dc40-11e8-9e9d-628123c6598c.png)
FIg2. SIFT detector + descriptor

![image](https://user-images.githubusercontent.com/36166137/47734387-9a53c900-dc40-11e8-935f-24630a0aeceb.png)
Fig3. SIFT detector + TFeat descriptor

![image](https://user-images.githubusercontent.com/36166137/47734556-e69f0900-dc40-11e8-97bd-e3cf2a6f62ce.png)
Fig4. BRISK detector + TFeat descriptor

The result is SIFT > BRISK detector + TFeat > BRISK > SIFT detector + TFeat . So Is TFeat really worse than SIFT ?

**Comment by hurricane2018** [comment]
In addition, we found the result is better if we do not recitify the extracted patch.

**Comment by vbalnt** [comment]
Hi @hurricane2018, you need to play around with the parameters of the relative extent of the patch extraction around keypoints. SIFT points for example are quite small so there is a magnification factor of 7. Your images above show that BRISK keypoints + TFeat give the best result, and that's because I guess you used the default `mag_factor` of 3.

Each opencv detection method has its own peculiarities, and you need to play around with the parameters when moving from one to another. In our case, we use TFeat with BRISK keypoints and as you see this configuration works quite well.

For the rectification, it might be slightly better to match unrectified patches in some cases, but if you dont rectify w.r.t the dominant angle, your method wont be able to match across heavy rotations.

**Comment by rafis** [comment]
Try **7.9** if you are using default SIFT keypoint detector parameters.

I have a question when UBC all trained params will be ready? The benefit of descriptors like SURF and SIFT that they are independent of dataset and your's descriptors are kinda overfitted over different UBC datasets. I'm getting better results with SIFT/SURF descriptors on most of my images. Currently **yosemite** pretrained parameters are best.
