### ISSUE TITLE
Evaluation of dataset

### ISSUE THREAD

**Issue by manyids2** [vbalnt/tfeat#2]
Dear vbalnt,

Thank you very much for open sourcing the code, it is very easy to read. 
I would like to point out a certain thing. In the [eval section](https://github.com/vbalnt/tfeat/blob/master/tensorflow/train/tfeat/train_tfeat.py#L211), there needs to be an update of the offset ( `offset += FLAGS.batch_size` ).

Thank you again, 
Best Regards,
ManyIds

**Comment by vbalnt** [comment]
Thanks, although credit goes to @edgarriba he wrote the tensorflow version.

Paging @edgarriba for your question.

**Comment by edgarriba** [comment]
@manyids2 did you manage to reproduce paper results with TF code?

**Comment by manyids2** [comment]
@edgarriba 
Dear Edgar,

No, I have not been able to reproduce the results with the TF code. 

Sincerely,
Manyids
