### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by rodrigo-reboucas** [vbalnt/tfeat#3]
Could you send the link to the input_video.webm and object_img.png files?

Because the software presents this message:
File "tfeat_demo.py", line 220
    print "Not enough matches are found with TFEAT - %d/%d" % (len(good1), MIN_MATCH_COUNT)

**Comment by edgarriba** [comment]
you could just create your own template, check this OpenCV tutorial where it's explained what you'll need
http://docs.opencv.org/master/d1/de0/tutorial_py_feature_homography.html
