### ISSUE TITLE
invalid dataset link

### ISSUE THREAD

**Issue by Danee-wawawa** [vbalnt/tfeat#8]
Dear vbalnt,
Thank you very much for sharing the code.
I met a problem that the link of "patches-dataset" in the web "https://github.com/vbalnt/UBC-Phototour-Patches-Torch" is invalid. Can you share me a new one? 
Thank you,
Best regards,
Dandan li.

**Comment by vbalnt** [comment]
Links are now updated 

https://github.com/vbalnt/UBC-Phototour-Patches-Torch
